id: A515C8BF1
title: 'Blazing Splendour of Good Fortune: A Prayer for the Spread of the Teachings
  of the Katok Tradition'
type: translation
pechas:
- I7DF2D012
- I5081E473
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:06:57.203602
  last_modified_at: 2023-01-04 12:06:57.203606
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I7DF2D012/B431: D5F6
  I5081E473/962B: D5F6
